### ISSUE TITLE
Übersetzungsregeln CSP+

### ISSUE THREAD

**Issue by naboga** [WAntonia/TINF18C_Team_3_DD2AML-Converter#15]
Übersetzungsregel von CSP+ für CAEX Version 2.15 und 3.0.

**Comment by Maruny** [comment]
Derzeitige Probleme:
- Fehlermeldung am Ende trotz kompletten Durchlauf der cspp Datei
- Umsetzung der Referenzen innerhalb der cspp Datei
- "Regeln innerhalb von Regeln" aufrufen

**Comment by WAntonia** [comment]
Lauffähige CSP+ Regeldatei für CAEX 2.15 und CAEX 3.0.
