### ISSUE TITLE
Anpassung GUI Tool

### ISSUE THREAD

**Issue by naboga** [WAntonia/TINF18C_Team_3_DD2AML-Converter#17]

**Comment by WAntonia** [comment]
Auswahl zwischen CAEX 2.15 und CAEX 3.0 muss eingefügt werden.
CAEX 2.15 soll als Standard ausgewählt werden.

**Comment by Maruny** [comment]
GSD2AML geändert zu DD2AML, Auswahl zwischen den Versionen und ein neues Logo hinzugefügt.
