### ISSUE TITLE
Business Case überarbeiten

### ISSUE THREAD

**Issue by naboga** [WAntonia/TINF18C_Team_3_DD2AML-Converter#2]
an die neuen Gegebenheiten anpassen:

- eine Person weniger im Team

- dadurch verändert sich der Zeitplan

- die Berechnungen zu den Kosten ändern sich

**Comment by WAntonia** [comment]
Business Case wurde überarbeitet.

- [x]  Inhaltsverzeichnis wurde hinzugefügt
- [x] Zeiten wurden, wo nötig, angepasst

Personen und Kostenanpassungen müssen laut Herrn Rentschler nicht vorgenommen werden, da der Business Case zu Beginn eines Projektes erstellt wird.
Desweiteren wurden Risiken, wie Personalverlust bereits im Business Case aufgeführt.
