### ISSUE TITLE
Remove and ignore compilation output

### ISSUE THREAD

**Issue by VuQuangPhuc** [WAntonia/TINF18C_Team_3_DD2AML-Converter#21]
The folders `/bin/*` and `/obj/*`should be removed from this repository.
obj are cache files generated as part of the build process.
bin contains the finals builds.
They are both outputs of the compilation process and can be rebuild from the other files.
Storing them in a repository is a waste of space.

Git is not very good with binary files (at least without [git-lfs](https://git-lfs.github.com/)). It cannot diff binary files. It will instead upload and store the entire file pretty much forever. This makes cloning a repository really painful.

Please read this for more information on what to commit to a repository and what not:
https://docs.microsoft.com/en-us/azure/devops/repos/git/manage-large-files?view=azure-devops

You can use this site to generate gitignore files for future projects: gitignore.io

Ignoring already committed files is unfortunately not enough as they are still being tracked by git.

Please refer to this guide on how to remove these folder from the repository and its history: https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

An alternative is to hard reset a local copy of this repository to a point when they have not yet been committed, add your files and a gitignore file and force push.
This should however be done with caution as progress could be permanently lost!

**Comment by WAntonia** [comment]
The bin and obj folders were removed including their history.
