### ISSUE TITLE
MOD Library

### ISSUE THREAD

**Issue by naboga** [WAntonia/TINF18C_Team_3_DD2AML-Converter#22]
Moduldokumentation für das Converter Modul

Inhalt:
-  Modul Anforderungen
-  Analyse
-  Design
-  Implementierung
-  Modultests
-  Zusammenfassung
-  Anhang

**Comment by naboga** [comment]
erste Version:

- Abgrenzung zu Converter
- mit CAEX Versionsauswahl
- soweit ausgefüllt, wie es aktueller Implementierungsstand zulässt

**Comment by naboga** [comment]
zweite Version:
- mit Analyse
- mit Desgin und Risiken

**Comment by naboga** [comment]
zusätzliche Informationen:
- Anahng und System Tests

es fehlt noch die Erklärungen zu den Übersetzungsregeln

**Comment by WAntonia** [comment]
Übersetzungsregeln für IODD und CSP+ wurden hinzugefügt.
