### ISSUE TITLE
Dateien in PROJECT Ordner hochladen und Wiki aktualisieren

### ISSUE THREAD

**Issue by naboga** [WAntonia/TINF18C_Team_3_DD2AML-Converter#25]
gesamte Dokumentation zum Projekt 
- im PROJECT Ordner hochladen
- als File im original Format
- als PDF File

Wiki mit aktuellen Informationen füllen
- SRS
- SAS
- Mods (individuelle Bearbeiter)
- User Manual

Readme Dateien hochladen

**Comment by naboga** [comment]
neue Dokumente hochgeladen:
- CRS

**Comment by naboga** [comment]
Dokumente überarbeitet:
- Gantt Chart
- Projektplan

**Comment by naboga** [comment]
hochgeladene Dokumente:
- SAS
- Mod.md

**Comment by Maruny** [comment]
- [ x] GUI MOD hochgeladen

**Comment by naboga** [comment]
- MOD AML Packager
- MOD Logger
- User Manual

**Comment by naboga** [comment]
- MOD Converter

**Comment by WAntonia** [comment]
- [x] STP
- [x] STR
- [x] MeetingMinutes
- [x] BC

**Comment by naboga** [comment]
- CLI
- MOD Library
