### ISSUE TITLE
MOD GUI

### ISSUE THREAD

**Issue by naboga** [WAntonia/TINF18C_Team_3_DD2AML-Converter#7]
Moduldokumentation für das GUI Modul
Inhalt:
- Modul Anforderungen
- Analyse
- Design
- Implementierung
- Modultests
- Zusammenfassung
- Anhang

**Comment by WAntonia** [comment]
- [x] GUI Modul Test Cases

**Comment by Maruny** [comment]
MOD GUI ausgefüllt und aktualisiert
