### ISSUE TITLE
System Test Plan

### ISSUE THREAD

**Issue by naboga** [WAntonia/TINF18C_Team_3_DD2AML-Converter#9]
Dieses Dokument spezifiziert die Teststrategie und den Testumfang. Damit kann das SRS verifiziert werden und Testfälle werden aufgestellt. Außerdem bildet es die Grundlage für den Systemtestbericht

**Comment by WAntonia** [comment]
Erste Version ohne detaillierte Tests fertig

**Comment by WAntonia** [comment]
- [x] GUI Modul Tests

- [x] CLI Modul Tests

- [x] Converter Modul Tests
